apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: kube-system
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/db
